### ISSUE TITLE
Navigation bar/page layout

### ISSUE THREAD

**Issue by akuyper** [NUstat/ISDStutorials#2]
I got the GitHub action to build and deploy the pkgdown site to work automatically. 

- [x] Update pkgdown layout

I think you will want use the same layout they used in the [dsbox tutorials](https://github.com/rstudio-education/dsbox/blob/main/_pkgdown.yml). A dataset page and tutorial reference page seems like the best layout for these.

Just similarly update the `_pkgdown.yml`. 

**Note:** If you make updates to the tutorials, I'm almost certain you will need me to redeploy them on my machine so the edits go through

**Comment by dsass1** [comment]
updated tutorial and function layout. Could still perhaps use some further updates at some point.
